import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import react from '@vitejs/plugin-react';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.tsx',
                'resources/js/chemicaldelivery.tsx',
                'resources/js/chemicaldeliverylist.tsx',
                'resources/js/chemicaljobcardlist.tsx',
                'resources/js/chemicalproductlist.tsx',
                'resources/js/createjobcard.tsx',
                'resources/js/jobcardReport.tsx',
                'resources/js/reactdeliveriescreate.tsx',
                'resources/js/reactdeliverylist.tsx',
                'resources/js/reactjoblist.tsx',
                'resources/js/reactproduct.tsx',
                'resources/js/reactorderlist.tsx',
                'resources/js/chemicaljobcard.tsx',
                'resources/js/stockadjustment.tsx',
                'resources/js/chemicalorderlist.tsx',
                'resources/js/chemicalorder.tsx',
                'resources/js/about.tsx',
                'resources/js/chemicalformula.tsx',
                'resources/js/chemicalmaterial.tsx',
                'resources/js/receivestock.tsx',
                'resources/js/rawmaterial.tsx',
            ],

            refresh: true,
        }),
        react(),
    ],
    build: {
        rollupOptions: {
            output: {
                // Entries are named from the `input` list above, so they are unique
                // by construction — safe to leave un-hashed and readable.
                entryFileNames: 'assets/[name].js',

                // Shared chunks are generated by Rollup and its `[name]` is derived
                // from whichever module it picks. Two chunks can land on the same
                // name and silently overwrite each other — which is how React ended
                // up inside a file called createLucideIcon.js. Nothing references
                // these filenames, so hashing them costs nothing and prevents it.
                chunkFileNames: 'assets/chunk-[hash].js',

                assetFileNames: 'assets/[name].[ext]',
            },
        },
    },
});